# 1. REDIRECCIÓN OBLIGATORIA: Todo lo que entre por HTTP (puerto 80) se va a HTTPS (443)
server {
    listen 80;
    server_name wattimizer.com www.wattimizer.com api.wattimizer.com;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# 2. SERVIDOR PRINCIPAL SEGURO (HTTPS - Puerto 443)
server {
    listen 443 ssl;
    server_name wattimizer.com www.wattimizer.com api.wattimizer.com;
    server_tokens off;

    # Rutas absolutas de los certificados
    ssl_certificate /etc/letsencrypt/live/wattimizer.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wattimizer.com/privkey.pem;

    # Optimización de seguridad SSL estándar
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Servir Frontend de Angular
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Redirección a la API REST de Spring Boot
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Redirección para el canal de WebSockets de telemetría
    location /ws-iot {
        proxy_pass http://backend:8080/ws-iot;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}