spring.application.name=jwt-auth-backend-demo

# 1. Configuración de la Base de Datos (Supabase / PostgreSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de JPA / Hibernate
# "update" intenta actualizar la BD (crear las tablas si no existen), si cambias el código Java (útil en desarrollo) pero NO crea hipertablas automáticamente
# "validate" solo comprueba que coincidan (más seguro si ya tienes el SQL hecho)
# Cambiamos a 'update' para no borrar las tablas de Supabase
spring.jpa.hibernate.ddl-auto=validate
# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.default_schema=auth_angular_spring_demo

# Dialecto (opcional en versiones nuevas, pero bueno para asegurar)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

mqtt.url=tcp://localhost:1883
mqtt.username=${MQTT_USER:gateway-service}
mqtt.password=${MQTT_PASSWORD:s3cr3t}


jwt.secret=${JWT_SECRET:esta_es_una_clave_temporal_de_32_bytes_desarrollo}

app.admin.secret=${ADMIN_KEY:clave_maestra_desarrollo_daw_2026}